user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events { worker_connections 1024; }

http {
  sendfile on;
  tcp_nopush on;
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  access_log /var/log/nginx/access.log;

  upstream api_up {
    server api:3002;
  }
  upstream sso_up {
    server sso:3001;
  }
  upstream obj_up {
    server objectstore:8082;
  }

  server {
    listen 80;
    server_name _;

    location = /apihealth {
      access_log off;
      proxy_pass http://api_up/health;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    if ($http_x_user_id != "") {
        return 400;
    }

    location /api/ {

      auth_request /auth;  
      auth_request_set $auth_user_id $upstream_http_x_user_id;
      auth_request_set $auth_user_email $upstream_http_x_user_email;  

      proxy_pass http://api_up/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-User-Id $auth_user_id;  
      proxy_set_header X-User-Email $auth_user_email;  
    }

    location /sso/ {
      proxy_pass http://sso_up/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /files/ {
      proxy_pass http://obj_up/;
      proxy_set_header Host $host;
    }

    location = /auth {
        internal;
        proxy_pass http://sso_up/auth;  
        proxy_set_header Authorization $http_authorization;  
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ =404; 
    }

    location /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'UP';
    }
  }
}
