version: "3.9"
services:
  bot:
    build: ./bot/
    restart: always 
    ports:
      - "5157:8000"
    environment:
      - "FLAG=ASIS{test-flag}"
      - "CAPTCHA_SECRET="
  web:
    image: nginx
    restart: always 
    ports:
      - "20570:80"
    volumes:
      - ./app/static:/var/www/html:ro
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      