version: "3.9"
services:
  bot:
    build: ./bot/
    restart: always 
    ports:
      - "5125:8000"
    environment:
      - "FLAG=ASIS{test-flag}"
      - "CAPTCHA_SECRET="
      - "WEB_DOMAIN=dangling.asisctf.com"
  web:
    image: php@sha256:93ac377d33f857707c7684416504d23fe05da32dc9452789a02d382ec5d13184
    volumes:
      - ./web/:/var/www/html/:ro
    restart: always 
    ports:
      - "20250:80"
