version: "3.8"

services:
  web:
    build: .
    container_name: injection-planner-benchmark
    ports:
      - "5104:8080"
    restart: unless-stopped
    networks:
      - injection-planner-network

networks:
  injection-planner-network:
    driver: bridge
